name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
      working-directory: /CSE115/socialshopper
    - name: Run tests
      run: pub run test
      working-directory: /CSE115/socialshopper
